#!/usr/bin/env bash

# move to where the grading scripts reside
cd /autograder/source/

# Run our grading script, which will produce a results.json
python grade.py Section8Main PublicTestCases --outpre graph --gradescope
if [ $? -eq 0 ]
then
	echo "Python run returned 0"
else
	echo "Python run returned ($?), still copying over results.json"
fi
cp TestingTemp/results.json /autograder/results/

